import base64
import json
from datetime import datetime
from pathlib import Path
from email.mime.text import MIMEText
from typing import Optional, Any

import sys
from pathlib import Path
_mcp_dir = Path(__file__).parent.parent
sys.path.insert(0, str(_mcp_dir))

from auth.google_oauth import get_gmail_service
from config import get_config


VALID_PROGRAMS = ['BSCSE', 'BSEEE', 'LLB']


def _format_cgpa(cgpa):
    """Format CGPA to 2 decimal places."""
    return f"{cgpa:.2f}" if isinstance(cgpa, (int, float)) else cgpa


def _build_email_body(audit_result: dict, include_full_report: bool = True) -> str:
    """Build plain-text email body from audit_result dict."""
    student_id = audit_result.get('student_id', 'Unknown')
    program = audit_result.get('program', 'Unknown')
    audit_level = audit_result.get('audit_level', 3)
    cgpa = audit_result.get('cgpa', 0.0)
    total_credits = audit_result.get('total_credits', 0)
    eligible = audit_result.get('eligible', False)
    deficiencies = audit_result.get('deficiencies', [])
    
    lines = []
    lines.append("NSU Graduation Audit Report")
    lines.append("=" * 40)
    lines.append("")
    lines.append(f"Student ID:    {student_id}")
    lines.append(f"Program:       {program}")
    lines.append(f"Audit Level:  L{audit_level}")
    lines.append(f"CGPA:          {_format_cgpa(cgpa)}")
    lines.append(f"Total Credits: {total_credits}")
    lines.append("")
    
    if eligible:
        lines.append("Status: ✓ ELIGIBLE FOR GRADUATION")
    else:
        lines.append("Status: ✗ NOT ELIGIBLE")
    
    lines.append("")
    
    if deficiencies and not eligible:
        lines.append("Deficiencies:")
        for i, dept in enumerate(deficiencies, 1):
            lines.append(f"  {i}. {dept}")
        lines.append("")
    
    if include_full_report:
        result_text = audit_result.get('result_text', '')
        if result_text:
            lines.append("")
            lines.append("=" * 40)
            lines.append("FULL AUDIT REPORT")
            lines.append("=" * 40)
            lines.append("")
            lines.append(result_text)
    
    lines.append("")
    lines.append("-" * 40)
    lines.append(f"Generated by NSU Audit Core — Department of {program}")
    
    return "\n".join(lines)


def send_email(
    to: str,
    audit_result: dict,
    subject: Optional[str] = None,
    cc: Optional[str] = None,
    include_full_report: bool = True
) -> dict[str, Any]:
    """
    Send a graduation audit result email via Gmail API.
    
    Args:
        to: Recipient email address
        audit_result: Result dict from run_audit
        subject: Optional custom subject (default: "NSU Graduation Audit Result — Student {student_id}")
        cc: Optional CC address
        include_full_report: Whether to include full audit report text
    
    Returns:
        {message_id, status: "sent", sent_at, recipient: to} or {status: "failed", error: <message>}
    """
    try:
        config = get_config()
        
        student_id = audit_result.get('student_id', 'Unknown')
        program = audit_result.get('program', 'Unknown')
        
        if subject is None:
            subject = f"NSU Graduation Audit Result — Student {student_id}"
        
        body = _build_email_body(audit_result, include_full_report)
        
        message = MIMEText(body, 'plain')
        message['to'] = to
        if cc:
            message['cc'] = cc
        message['subject'] = subject
        
        gmail_service = get_gmail_service(
            config['token_path'],
            config['credentials_path'],
            config['reauth']
        )
        
        encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
        
        body_msg = {
            'raw': encoded_message
        }
        
        result = gmail_service.users().messages().send(
            userId='me',
            body=body_msg
        ).execute()
        
        message_id = result.get('id', '')
        sent_at = datetime.utcnow().isoformat() + 'Z'
        
        _log_email(to, student_id, sent_at, message_id)
        
        return {
            'message_id': message_id,
            'status': 'sent',
            'sent_at': sent_at,
            'recipient': to
        }
    
    except Exception as e:
        return {
            'status': 'failed',
            'error': str(e)
        }


def _log_email(to: str, student_id: str, sent_at: str, message_id: str):
    """Log sent email to local history file."""
    history_path = config = get_config()['history_path']
    
    history_entry = {
        'type': 'email',
        'to': to,
        'student_id': student_id,
        'sent_at': sent_at,
        'message_id': message_id
    }
    
    history_path.parent.mkdir(parents=True, exist_ok=True)
    
    if history_path.exists():
        with open(history_path, 'r') as f:
            try:
                history = json.load(f)
            except json.JSONDecodeError:
                history = []
    else:
        history = []
    
    history.append(history_entry)
    
    with open(history_path, 'w') as f:
        json.dump(history, f, indent=2)
